#!/bin/bash
#
##
#
DRIVER=/usr/src/nvidia-driver
kernelversion=`uname -r`

yum -y erase dkms

# Build new driver if it doesn't exist
if [ -e /lib/modules/$kernelversion/kernel/drivers/video/nvidia.ko ] ; then
    echo "NVIDIA driver already exists for this kernel." >&2
    logger "nvidia.sh: NVIDIA driver already exists for this kernel"
else
    echo "Building NVIDIA driver for kernel $kernelversion" >&2
    logger "nvidia.sh: Building NVIDIA driver for kernel $kernelversion"
    sh $DRIVER -K -k $kernelversion -s -n 2>1 > /dev/null

    if [ -e /lib/modules/$kernelversion/kernel/drivers/video/nvidia.ko ] ; then
        echo "   SUCCESS: Driver installed for kernel $kernelversion" >&2
        logger "nvidia.sh:   SUCCESS: Driver installed for kernel $kernelversion"
    else
        echo "   FAILURE: See /var/log/nvidia-installer.log" >&2
        logger "nvidia.sh:   FAILURE: See /var/log/nvidia-installer.log"
    fi
fi

cat /etc/redhat-release|grep "release 6."
if [ $? == 0 ]; then
        init 3
else
      	systemctl start display-manager
fi


exit 0

