---
#Travis CI Job File. Feel free to extend. Have a look at the special cases in the Gemfile for Ruby 1.9
dist: xenial
sudo: false
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.3
stages:
  - static
  - spec
  -
    if: tag =~ ^v\d
    name: deploy
matrix:
  fast_finish: true
  include:
    -
      env: PUPPET_VERSION="~> 6.0" CHECK=test PARALLEL_TEST_PROCESSORS=4
      stage: spec
    -
      env: PUPPET_VERSION="~> 5.0" CHECK=test PARALLEL_TEST_PROCESSORS=4
      rvm: 2.4.5
      stage: spec
    -
      env: DEPLOY_TO_FORGE=yes
      stage: deploy
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: icinga
  password:
    secure: "U4FeZmywLvOLXRv30EoWoWa2Eey41Zn2bE9NTVzDtJ0U6dR4g22aGpe7JsJRfetV7+8gxHfnxhx4vNSPUqt2wKT0AUTMAAiadsbKypjLV7VHf+owjyvhRBNpUFFhxYJwZuyBBJdAaw0DBu/vZa345tCKXOMg9DADJ900Z1l47X137QMMVHyLPJ+NUqKD/ONPXf0NDCGXnZLQwFVQw7rbYmYR2O5kb5x1Fkq4b3onvHOIe5obkj5DFUjICw2nPdp/f+VVg80EDCl/IagCvrKMAryeoF2GqYijjm6arxruxwW+igR1LfuXmDLWP4f/Xc/IzcciwIWD6P1cKoqId+TfdWE8K4TJt6pZCWA3CK/lk2KsdxHJeqwpoK18AglI86UAmK5pwSnDhm4OgqADVRUtOrq7k1IMHWs/T49q9PgHqn2CwuIvmSAYdLq7peLzizCZ0ZrRkFfnXNG8hf/hBNTrS0DdJmJnGkZk7gCJJQUgprGD5FSnOBFV0w9cXNLbXR9RSPKTVdnBZnCl3oyXLlMAeKrHQ6fvFHfmfpcKmufxTF32jkWxt9fnHgoNFZHzs0aY1B/zRw4GMmgHgobVQY/czw2iMzMmKvoAGB8aO4EtToKFkL6hcBxEtNCfXF3EJZykTim+AT7SfHSeShXQ+Isy2kd2Oeamiurrm5iS27FkzjQ="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
